[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/pawpaws-dog-grooming/Dockerfile"
buildCommand = "pnpm --filter pawpaws-dog-grooming build"
watchPatterns = [
	"/apps/pawpaws-dog-grooming/**",
	"/packages/**",
	"package.json",
	"pnpm-lock.yaml",
]

[deploy]
multiRegionConfig = { "us-west2" = { numReplicas = 1 } }
runtime = "V2"
numReplicas = 1
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
sleepApplication = true
useLegacyStacker = false
ipv6EgressEnabled = false
restartPolicyType = "ALWAYS"
healthcheckTimeout = 300
